### ISSUE TITLE
question about eq.8

### ISSUE THREAD

**Issue by wangchx67** [wyf0912/ExposureDiffusion#1]
Hi, thanks for your great work. However, I hardly understand how to derive the Eq.8. Can you provide more details?

**Comment by wyf0912** [comment]
Eq. 8 is based on the wave-particle duality, i.e., the incremental part from the increased exposure time should obey the Poisson distribution. Specifically, the average number of events/the rate of the Poisson distribution should be related to the luminance of the scene.

**Comment by wangchx67** [comment]
Thanks. Actually I do not explictly know how to derive parameters of this distribution (Eq.8), i.e., how to get the $X_{t}-X_{-1}/K$ and $(\lambda_{t}-\lambda_{t-1})X_{ref}/\lambda_{ref}K$. I also do not find in appendix.

**Comment by wangchx67** [comment]
I have understood this process. Thanks!
Besides, the caption of Fig.9 seems to be wrong.

**Comment by wyf0912** [comment]
> Thanks. Actually I do not explictly know how to derive parameters of this distribution (Eq.8), i.e., how to get the Xt−X−1/K and (λt−λt−1)Xref/λrefK. I also do not find in appendix.

glad to hear that you have solved the problem

**Comment by wyf0912** [comment]
> I have understood this process. Thanks! Besides, the caption of Fig.9 seems to be wrong.


Why the caption of Fig.9 seems to be wrong? Fig. 9 is a visualization of the vanilla conditional diffusion models.
