### ISSUE TITLE
About Training Time

### ISSUE THREAD

**Issue by conutqiqi** [wyf0912/ExposureDiffusion#10]
I appreciate your research efforts. I have a keen interest in your work. I would like to retrain the model following your paper. Could you provide an estimate of the actual training time for reference?
Thank you!

**Comment by wyf0912** [comment]
Around one day. I can not remember exactly.

**Comment by conutqiqi** [comment]
Thank you for your answer, and I would like to ask what type of graphics card the author used to run the program at that time?

**Comment by wyf0912** [comment]
RTX3090 or A5000
