### ISSUE TITLE
关于论文中的公式的疑惑.

### ISSUE THREAD

**Issue by NUAA-XSF** [wyf0912/ExposureDiffusion#2]
你好, 关于这篇论文中公式8, 条件概率公式 
$q(X_{t-1}|X_{t}, X_{ref}) ={\cal P}(\frac{X_{t-1}-X_{t}}{K};\frac{(\lambda_{t-1}-\lambda_{t})X_{ref}}{\lambda_{ref}K})$ 
是否应该写成这样 
$q(X_{t-1}|X_{t}, X_{ref}) ={\cal P}(X_{t-1};\frac{X_{t}}{K}+\frac{(\lambda_{t-1}-\lambda_{t})X_{ref}}{\lambda_{ref}K})$ 
更加合适. 公式9也是如此.

**Comment by NUAA-XSF** [comment]
还有 Algorithm 1 的第8行
$X_{t-1} \sim p_\theta( X_{t-1} | X_t)$
其中, $X_{t-1}$ 是否也可以从 $q$ 中采样, 和一般的扩散模型一样
$X_{t-1} \sim q( X_{t-1} | X_t, X_{ref})$

**Comment by wyf0912** [comment]
> 还有 Algorithm 1 的第8行 Xt−1∼pθ(Xt−1|Xt) 其中, Xt−1 是否也可以从 q 中采样, 和一般的扩散模型一样 Xt−1∼q(Xt−1|Xt,Xref)

这个采样是从我们的优化目标推导出来的

其次 如果使用一般的扩散模型的训练采样 可能会有性能随着迭代次数的增加而下降的问题 （因为对于Denoise任务 PSNR已经相对很高了）

**Comment by wyf0912** [comment]
> 你好, 关于这篇论文中公式8, 条件概率公式 q(Xt−1|Xt,Xref)=P(Xt−1−XtK;(λt−1−λt)XrefλrefK) 是否应该写成这样 q(Xt−1|Xt,Xref)=P(Xt−1;XtK+(λt−1−λt)XrefλrefK) 更加合适. 公式9也是如此.

这个的物理含义是增量信号的增量部分服从泊松分布  增量部分X_{t-1}-X_t不应该影响已经接受到的信息X_t

**Comment by NUAA-XSF** [comment]
> > 你好, 关于这篇论文中公式8, 条件概率公式 q(Xt−1|Xt,Xref)=P(Xt−1−XtK;(λt−1−λt)XrefλrefK) 是否应该写成这样 q(Xt−1|Xt,Xref)=P(Xt−1;XtK+(λt−1−λt)XrefλrefK) 更加合适. 公式9也是如此.
> 
> 这个的物理含义是增量信号的增量部分服从泊松分布 增量部分X_{t-1}-X_t不应该影响已经接受到的信息X_t

感谢回复!
增量部分服从passion分布. 但公式8的泊松分布是关于 增量信号 $\frac{X_{t-1}-X_{t}}{K}$ 的, 而不是 关于 $X_{t-1}$ 的, 而等式左边的条件概率公式 是 关于 $X_{t-1}$ 的. 我的意思是可能这个等式是不成立的.

**Comment by wyf0912** [comment]
> > > 你好, 关于这篇论文中公式8, 条件概率公式 q(Xt−1|Xt,Xref)=P(Xt−1−XtK;(λt−1−λt)XrefλrefK) 是否应该写成这样 q(Xt−1|Xt,Xref)=P(Xt−1;XtK+(λt−1−λt)XrefλrefK) 更加合适. 公式9也是如此.
> > 
> > 
> > 这个的物理含义是增量信号的增量部分服从泊松分布 增量部分X_{t-1}-X_t不应该影响已经接受到的信息X_t
> 
> 感谢回复! 增量部分服从passion分布. 但公式8的泊松分布是关于 增量信号 Xt−1−XtK 的, 而不是 关于 Xt−1 的, 而等式左边的条件概率公式 是 关于 Xt−1 的. 我的意思是可能这个等式是不成立的.

$q(X_{t-1}|X_t, X_{ref})$这个format只是为了说明X_{t-1}的分布是与$X_t, X_{ref}$有关的，具体的关系是$\frac{X_{t-1}-X_t}{K}$服从以分号后面那项为比率的泊松分布的

你提出的写法似乎不是很准确

**Comment by NUAA-XSF** [comment]
谢谢,我理解了.
