### ISSUE TITLE
.db files missing

### ISSUE THREAD

**Issue by neiterman21** [wyf0912/ExposureDiffusion#3]
I'm trying to train on SID dataset and I see the code is looking for SID_Sony_target_Raw.db file but I can't seem to find it.

**Comment by wyf0912** [comment]
It seems that "SID_Sony_target_Raw.db" is only used when trained using sRGB image?

**Comment by neiterman21** [comment]
no it is used on RAW.
other .db files used for sRGB but I can't find them ither.

**Comment by wyf0912** [comment]
You can use "util/lmdb_data.py" to process the dataset to get "SID_Sony_target_Raw.db"
